version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Setting up AWS Credentials...
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Validating CloudFormation templates...
      - aws cloudformation validate-template --template-body file://cloudformation/iam/iam-role.yaml
  post_build:
    commands:
      - echo CloudFormation template validated successfully.

artifacts:
  files:
    - '**/*'
