version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
  build:
    commands:
      - echo Validating CloudFormation templates...
      - aws cloudformation validate-template --template-body file://cloudformation/iam/iam-role.yaml
  post_build:
    commands:
      - echo CloudFormation template validated successfully.

artifacts:
  files:
    - '**/*'
