version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli  # Ensure AWS CLI is installed
      - aws --version  # Verify AWS CLI version (v2 preferred)
      
  build:
    commands:
      - echo Verifying CloudFormation template path...
      - ls -l cloudformation/iam/iam-role.yaml  # List the directory to ensure the file exists
      - echo Validating CloudFormation template...
      - aws cloudformation validate-template --template-body file://cloudformation/iam/iam-role.yaml
      - echo CloudFormation template validated successfully.

  post_build:
    commands:
      - echo Deploying CloudFormation stack...
      - aws cloudformation deploy \
          --template-file cloudformation/iam/iam-role.yaml \
          --stack-name my-stack-name \
          --parameter-overrides file://cloudformation/iam/parameters.json

artifacts:
  files:
    - cloudformation/**/*   # Include all CloudFormation templates in the output artifact
